### ISSUE TITLE
Собрать и выложить контент для разделов Выступления и Статьи

### ISSUE THREAD

**Issue by beevee** [skbkontur/skbkontur.github.io#10]
- [x] собрать выступления в гугл-таблицу
- [x] выложить собранные выступления на сайт
- [x] расставить ссылки на сайты конференций
- [x] собрать статьи в гугл-таблицу
- [x] выложить собранные статьи на сайт

**Comment by beevee** [comment]
Контент по выступлениям собрал в гуглдоке, осталось наполнить.

**Comment by tihonove** [comment]
Запилил первую версию статей. Мы пообщались с Катей, кажется, что там должны быть какие-то описания, текст в общем какой-то. Надо учесть при сборе контента.
Мы на верстку ещё посмотрим, может что-то подвигаем, но кажется, что радикально ничего не изменится.
