### ISSUE TITLE
Нелогичная ссылка в Выступлениях

### ISSUE THREAD

**Issue by beevee** [skbkontur/skbkontur.github.io#12]
Для меня стало неожиданностью, что ссылка с названия доклада ведет на презентацию.

Презентация - это вспомогательный материал, и почти никогда по одной только презентации нельзя понять смысл доклада. Кажется, что основной материал - это все-таки видео, а презентация должна существовать как вспомогательный для тех, кому на видео не разглядеть текст или код.

Не уверен, что это лучший вариант, но я бы сделал так: ссылку с названия доклада тоже на видео, а презентацию положил отдельной ссылкой где-нибудь ниже.

Еще мнения? :)

**Comment by polecat89** [comment]
![default](https://cloud.githubusercontent.com/assets/15029003/19269869/4229800c-8fd6-11e6-9d0f-a35c60c85e81.png)
