### ISSUE TITLE
Добавить ссылку на Контур.Гайды

### ISSUE THREAD

**Issue by igorlukanin** [skbkontur/skbkontur.github.io#13]
https://guides.kontur.ru

**Comment by beevee** [comment]
Я не очень понял, для кого эта ссылка. Кто является конечным потребителем этих гайдов за пределами Контура?

**Comment by chipitsine** [comment]
вероятно, для внешнего потребителя был бы полезен фирменный стиль, напр. https://alfabank.ru/about/ads/logo/

гайды это, действительно, странная сущность, до сих пор не понимаю, зачем их во внешний мир вывесили

**Comment by igorlukanin** [comment]
@beevee Потребителями гайдов за пределами Контура должны быть дизайнеры, проектировщики интерфейсов. Я думаю, что как минимум с точки зрения полноты они будут интересны и позволят кому-то не наступить на грабли, проектируя интерфейсы вне Контура.

Самый интересный для внешнего читателя раздел — список знаний и навыков проектировщика: https://guides.kontur.ru/principles/uidesigner/

Хоть завтра публикуй в отраслевом издании. (Утрирую, но не сильно.)

**Comment by beevee** [comment]
Зафиксирую здесь свои мысли.

Я хочу, чтобы сайт был про технологии и ноу-хау, которыми Контур хочет поделиться с миром. Я не хочу делать каталог ссылок на все происходящее в Контуре. Я не хочу размещать пресс-кит и брендбук с правильными логотипами в кривых. Я не хочу размещать информацию для партнеров о том, как быть правильным партнером.

Что является технологиями и ноу-хау, а что — нет? Для меня очевидно, что библиотека Игоря Чевдаря GrEmit — это технология, которой нужно поделиться. Для меня очевидно, что доклад Вовы Кутового Keep Calm про дизайн — это ноу-хау, которым нужно поделиться. Я считаю, что статья на Хабре про то, как фрилансеру общаться с налоговой — это не для сайта про технологии и ноу-хау. Такая серия оценочных суждений.

Пока что я не могу принять решение про Гайды — не понимаю, куда их приткнуть, и стоит ли вообще. Ясно, что реализация Гайдов — тот же retail-ui — может при желании авторов попасть в раздел Open Source. Ясно, что статья про Гайды, в которой будет написана польза от этих Гайдов для внешнего мира, может попасть в раздел Статьи. Выступление про Гайды — понятно. Сами Гайды, без всякого комментария, без всякой подачи? Пока не знаю. Помогите понять.

**Comment by igorlukanin** [comment]
Как я уже писал, особенность Гайдов их полноте. Именно это делает их ноу-хау и побуждает делиться ими с миром. Думаю, мнение Сергея Соловьёва здесь значит больше моего, я скорее поднял вопрос. Поделюсь ссылкой с Сергеем.

**Comment by beevee** [comment]
Гайды логически не попадают ни в одну из существующих трех категорий на сайте. Следовательно, их придется делать четвертой страницей. Если делать четвертую страницу, то она не может содержать в себе только одну ссылку на другой сайт — нужен сопровождающий текст, какой-то промо-контент, может быть.

Если у кого-нибудь (у Сергея?) получится сделать такой промо-контент вокруг ссылки на Гайды, что для посетителя сайта будет ясно, зачем эта ссылка выложена — то я размещу с удовольствием.

**Comment by chipitsine** [comment]
не, про брендбук это была иллюстрация, что теоретически могло бы быть полезно внешнему миру (вместо гайдов). я не говорил, что брендбук надо на tech.skbkontur.ru, ему место где-нибудь на https://kontur.ru

**Comment by igorlukanin** [comment]
Resolved in fe577b61d7d1494f9c2e6e8eb771003b8c931ca3. Guides are open source, and they come with source code (https://github.com/skbkontur/retail-ui).
