### ISSUE TITLE
Улучшить сниппеты в поисковых системах

### ISSUE THREAD

**Issue by beevee** [skbkontur/skbkontur.github.io#16]

**Comment by safarov** [comment]
Сниппеты в google улучшили https://www.google.ru/search?hl=ru&as_q=&as_epq=&as_oq=&as_eq=&as_nlo=&as_nhi=&lr=&cr=&as_qdr=all&as_sitesearch=tech+skbkontur+ru&as_occt=any&safe=images&as_filetype=&as_rights=#newwindow=1&hl=ru&as_qdr=all&q=site:tech.skbkontur.ru
для страницы http://tech.skbkontur.ru/articles еще в процессе.
Яндекс пока не проиндексировал сайт - работаем дальше

**Comment by safarov** [comment]
яндекс проиндексировал https://yandex.ru/search/?lr=54&clid=1955454&win=190&msid=1476813259.92107.22903.28495&text=tech.skbkontur.ru&nomisspell=1&site=tech.skbkontur.ru
description главной пока не подхватил и еще http://tech.skbkontur.ru/en нет в индексе. Ждем правильного sitemap.xml

**Comment by safarov** [comment]
В google сниппеты по ключевым запросам лучше 
запрос "open sourse контур"
https://www.google.ru/search?hl=ru&site=webhp&source=hp&q=open+source+%D0%BA%D0%BE%D0%BD%D1%82%D1%83%D1%80&oq=open+source+%D0%BA%D0%BE%D0%BD%D1%82%D1%83%D1%80&gs_l=hp.3...1250.1250.0.2034.2.2.0.0.0.0.416.821.4-2.2.0....0...1c.1.64.hp..0.0.0.0.19UuNh6yA_s

https://yandex.ru/search/?lr=54&c2lid=1955454&msid=1478011376.61911.22890.4668&text=open%20source%20%D0%BA%D0%BE%D0%BD%D1%82%D1%83%D1%80

запрос "технологии контура"
https://yandex.ru/search/?text=%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8%20%D0%BA%D0%BE%D0%BD%D1%82%D1%83%D1%80&lr=54&clid=1955454 - тут на 2 месте, но сниппет не ок 

https://www.google.ru/search?q=%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8+%D0%BA%D0%BE%D0%BD%D1%82%D1%83%D1%80&hl=ru&biw=1368&bih=632&site=webhp&ei=n6oYWJztMMiS6ASgmKUo&start=0&sa=N - тут нас вообще нет 

в общем, дальше моих знаний уже не хватает, как улучшить ситуацию. Давайте обратимся к знающим, начальные требования по seo мы выполнили.

**Comment by safarov** [comment]
мы поднялись по запросам "технологии контур" и "open sourse контур"
