### ISSUE TITLE
Добавить в подвал раздела Выступления копирайт на фотографии

### ISSUE THREAD

**Issue by beevee** [skbkontur/skbkontur.github.io#18]
> Фотографии докладчиков взяты из видео выступлений и фотоархивов соответствующих конференций. Рядом с каждым выступлением есть ссылка на сайт конференции, который является источником фотографии.

**Comment by tihonove** [comment]
Лёша, ты мог бы показать пример какой-нибудь?

**Comment by beevee** [comment]
Давай сделаем надпись как на kontur.ru, только поместим в подвале над переключалкой языков. Если что, нас дизайнеры поправят :)
![2016-10-17_20-11-10](https://cloud.githubusercontent.com/assets/1009675/19443481/56593d18-94a6-11e6-80d8-d1daa48d7a42.png)

**Comment by tihonove** [comment]
@beevee , чорт, я так и не понял, как надо делать. Завтра зайду к тебе

**Comment by beevee** [comment]
Зависит от #17 (ссылки на сайты конференций).
