### ISSUE TITLE
Нам нужна favicon-ка

### ISSUE THREAD

**Issue by tihonove** [skbkontur/skbkontur.github.io#19]
и кажется, что заголовок страницы должен содержать не только название раздела, но какой-то общий контекст

![image](https://cloud.githubusercontent.com/assets/2770182/19420224/32771c68-9400-11e6-864b-387719e1a061.png)

Может такое же облачко воткнём?

**Comment by tihonove** [comment]
@beevee, что думаешь?

**Comment by beevee** [comment]
Нужны еще телефонные иконки такого сорта:

```
<!-- iPhone 6 Plus  -->
<link rel="apple-touch-icon" sizes="180x180" href="/theme/ver-344800201/images/iconIphone/apple-touch-icon-180x180.png" />
<!-- iPad and iPad mini -->
<link rel="apple-touch-icon" sizes="152x152" href="/theme/ver-344800201/images/iconIphone/apple-touch-icon-152x152.png" />
<!-- Retina iPad --> 
<link rel="apple-touch-icon" sizes="144x144" href="/theme/ver-344800201/images/iconIphone/apple-touch-icon-144x144.png" />
<!-- iPhone 6 and iPhone 5 and iPhone 4s  -->
<link rel="apple-touch-icon" sizes="120x120" href="/theme/ver-344800201/images/iconIphone/apple-touch-icon-120x120.png" />
<!-- Retina iPhone --> 
<link rel="apple-touch-icon" sizes="114x114" href="/theme/ver-344800201/images/iconIphone/apple-touch-icon-114x114.png" />
<!-- iPad 2 and iPad mini -->
<link rel="apple-touch-icon" sizes="76x76" href="/theme/ver-344800201/images/iconIphone/apple-touch-icon-76x76.png" />
<!-- Standard iPad --> 
<link rel="apple-touch-icon" sizes="72x72" href="/theme/ver-344800201/images/iconIphone/apple-touch-icon-72x72.png" />
<!-- Standard iPhone --> 
<link rel="apple-touch-icon" sizes="57x57" href="/theme/ver-344800201/images/iconIphone/apple-touch-icon-57x57.png" />
```

**Comment by beevee** [comment]
По заголовкам страниц порешаю в рамках поисковой оптимизации.

Фавиконки нужно стрельнуть на kontur.ru.

**Comment by tihonove** [comment]
Закрыва, для заголовка сделал отдельную ишью

**Comment by safarov** [comment]
проверено

`<link data-react-helmet=true href=/favicon.ico rel="shortcut icon">`

`<link data-react-helmet=true rel=apple-touch-icon sizes=114x114 href=/77a3656de5d182e1be36242d7c76aba2.png><link data-react-helmet=true rel=apple-touch-icon sizes=120x120 href=/f8a6d541a11a85cabceb0dce91a22090.png><link data-react-helmet=true rel=apple-touch-icon sizes=144x144 href=/7e76c981eb8593fbef00985fc80e3452.png><link data-react-helmet=true rel=apple-touch-icon sizes=180x180 href=/317d7214f4b62c193439b208bc444fab.png><link data-react-helmet=true rel=apple-touch-icon sizes=57x57 href=/c0d3b7560660d7cdeee101b45ae58592.png><link data-react-helmet=true rel=apple-touch-icon sizes=72x72 href=/fcd910fe5b3f994b741ea50bb50f51ca.png><link data-react-helmet=true rel=apple-touch-icon sizes=76x76 href=/9f419bebd4759fd1250f42ad7ce2d615.png>`
