### ISSUE TITLE
Добавить ссылку на email

### ISSUE THREAD

**Issue by tihonove** [skbkontur/skbkontur.github.io#2]
opensource@kontur,ru

**Comment by tihonove** [comment]
Надо бы придумать куда её всунуть. @beevee , может найдешь какой-нибудь пример на нашем (контуровском) сайте?

**Comment by beevee** [comment]
![2016-09-29_12-16-09](https://cloud.githubusercontent.com/assets/1009675/18944375/a79ce2b8-863e-11e6-9f0d-6760f19c37e0.png)

Я бы вместо политики обработки персданных положил в футер.
