### ISSUE TITLE
Сделать генерацию sitemap при сборке сайта

### ISSUE THREAD

**Issue by beevee** [skbkontur/skbkontur.github.io#20]
sitemap.xml должен лежать в корне

**Comment by tihonove** [comment]
robots.txt сделал, надо будет, как сделаем sitemap, добавить туда ссылку на sitemap.xml

**Comment by safarov** [comment]
почему в http://tech.skbkontur.ru/sitemap.xml в <lastmod>2016-9-18</lastmod> указан месяц 9 = сентябрь, должно же быть 10. 

И еще 

`<url>
<loc>http://tech.skbkontur.ru/ru/</loc>
<changefreq>daily</changefreq>
<priority>0.6</priority>
<lastmod>2016-9-18</lastmod>
</url>
<url>
<loc>http://tech.skbkontur.ru/ru/talks</loc>
<changefreq>daily</changefreq>
<priority>0.6</priority>
<lastmod>2016-9-18</lastmod>
</url>
<url>
<loc>http://tech.skbkontur.ru/ru/articles</loc>
<changefreq>daily</changefreq>
<priority>0.6</priority>
<lastmod>2016-9-18</lastmod>
</url>`
это дубли, что не хорошо. Может все же мы вручную пока sitemap подложим? страниц не так много, я сделаю правильный sitemap.xml, так как вести нужно на адреса со слешем, без слеша страницы отдают 301 код, что опять же не хорошо для поисковых роботов.

**Comment by tihonove** [comment]
Месяц поправлю. Не совсем понял, что там про слеши или там 301. @safarov , я не хочу ручной sitemap.xml, и предлагаю подступить так: ты сделаешь правильный sitemap.xml, а я сделаю его автогенерацию.

**Comment by safarov** [comment]
про 301 речь про вот это при повторном входе на такие страницы как http://tech.skbkontur.ru/talks или http://tech.skbkontur.ru/articles происходит 301-редирект на такие страницы как http://tech.skbkontur.ru/talks/ или http://tech.skbkontur.ru/articles/ и к ним добавляется слеш.

**Comment by tihonove** [comment]
Всё понял, просто в sitemap надо указать на стhаницы со слешем, чтобы не было лишних редиректов. Сути это не меняет -- генерить хотим автоматом. Правильно ли я понимаю, что надо поправить следующие моменты:
1. Правильный месяц
2. Убрать дубли
3. Страницы должны быть с слешиком

**Comment by safarov** [comment]
да верно, в качестве эталона - во вложении.
1. совсем правильно будет указывать в формате `<lastmod>2016-10-18T08:59:07+00:00</lastmod>`, но можно и `<lastmod>2016-10-18</lastmod>`
4. Для главной страницы должно быть `<priority>1.00</priority>`
[sitemap.zip](https://github.com/skbkontur/skbkontur.github.io/files/536031/sitemap.zip)

**Comment by safarov** [comment]
1.  `<changefreq>always</changefreq>`, сейчас daily, потом можно поменять значение, но сейчас лучше always, так как нам надо переиндексацию сайта, пусть чаще ходят

**Comment by safarov** [comment]
круто, спасибо
то что нужно http://tech.skbkontur.ru/sitemap.xml

**Comment by safarov** [comment]
отправил на переиндексацию
