### ISSUE TITLE
Закрыть от индексации грязный контент

### ISSUE THREAD

**Issue by beevee** [skbkontur/skbkontur.github.io#21]
См. псевдотеги noindex и атрибут rel="nofollow":

```
<span><!--noindex-->c 1988 года<!--/noindex--></span>

<a><!--noindex-->Ru<!--/noindex--></a>

<a><!--noindex-->En<!--/noindex--></a>

<span><!--noindex-->opensource@skbkontur.ru<!--/noindex--></span>

<a href="mailto:opensource@skbkontur.ru" rel="nofollow"> 
```

**Comment by safarov** [comment]
ага спасибо 
изменения вижу 

`<a rel=nofollow class=_5Y4ps92ZQK1h41VNaBxcQ href=mailto:opensource@skbkontur.ru data-reactid=102>`

`<noindex data-reactid=93><div class=_2tLw-35W7_nmXlautPdfPM data-reactid=94><footer class="_2uuI9divykC6A9Zkt0VTxx fixed-width-content" data-reactid=95><div class=_1ARXMPGhdsZm98FJHk6t7A data-reactid=96></div><span class=_2sraa28QlIUUGU6FKpr_bP data-reactid=97>c 1988 года</span><div class=_1a6QNIBvn-jo9oEk99xiJg data-reactid=98><a class=kr0VKqyNFaugcbKOCeEXt data-reactid=99>Ru</a><a href=/en data-reactid=100>En</a></div><div class=_2yPtwNMjBfb9J6kf8tYDMO data-reactid=101></div><a rel=nofollow class=_5Y4ps92ZQK1h41VNaBxcQ href=mailto:opensource@skbkontur.ru data-reactid=102><span class=icon data-reactid=103><span class=_2zALekCOCyHSuAPI0xP1k_ data-reactid=104></span></span><!-- react-text: 105 --> <!-- /react-text --><span class=_3j52uzMAp8NhB1J2WSNnKn data-reactid=106>opensource@skbkontur.ru</span></a></footer></div></noindex>`
