### ISSUE TITLE
Добавить мета-теги для соцсетей

### ISSUE THREAD

**Issue by beevee** [skbkontur/skbkontur.github.io#23]
```
<meta content="summary" name="twitter:card" />
<meta content="@skbkontur" name="twitter:site" />
<meta content="@skbkontur" name="twitter:creator" />
<meta content="article" property="og:type" />
<meta content="http://tech.skbkontur.ru" property="og:url" />
<meta content="--- то же самое, что в теге title ---" property="og:title" />
<meta content="--- то же самое, что в теге title ---" property="og:site_name" />
<meta content="--- то же самое, что в мета-теге description ---" property="og:description" />
<meta content="--- переложить к нам эту картинку: https://kontur.ru/theme/ver-344800201/common/images/logo_social.png" property="og:image" />
<link href="--- переложить к нам эту картинку: https://kontur.ru/theme/ver-344800201/common/images/logo_social.png" rel="image_src" />
<meta property="og:type" content="website"/>
```

**Comment by safarov** [comment]
facebook все равно тянет откуда-то неверный заголовок сайта, разбираемся дальше - тикет можно переоткрыть, так как задачу мы не решили 
![image](https://cloud.githubusercontent.com/assets/2157406/19465732/c546fe8a-951f-11e6-9760-b286976a463b.png)

**Comment by safarov** [comment]
в помощь https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Ftech.skbkontur.ru, по правилам 

Вот у нас все правильно указано

```
<meta data-react-helmet=true content=article property=og:type>
<meta data-react-helmet=true content=http://tech.skbkontur.ru property=og:url>
<meta data-react-helmet=true content="Open source технологии и решения компании СКБ Контур: Moira, DiTrace и многое другое" property=og:title>
<meta data-react-helmet=true content="Open source технологии и решения компании СКБ Контур: Moira, DiTrace и многое другое" property=og:site_name>
<meta data-react-helmet=true content="Open source технологии компании СКБ Контур. Moira — решение по уведомлениям из Graphite, DiTrace — трассировка запросов в распределенных системах и другие решения" property=og:description>
<meta data-react-helmet=true property=og:type content=website> 
```

но все равно валидатор показывает 

```
og:title    Open source
og:description  Open source технологии компании СКБ Контур
```

WTF?

**Comment by safarov** [comment]
В `<meta data-react-helmet=true content=/2c310c5fc1154922a96823017cd30fde.png property=og:image>` нужно урл на картинку прямой указать, вот так `<meta content="https://kontur.ru/theme/ver-1108166122/common/images/logo_social.png" property="og:image" />`
Леша, может картинку-то все же другую сделаем с лого Контур и рядом Open Source?

**Comment by safarov** [comment]
разобрался в чем дело, надо вот так что бы было 

```
<meta content="article" property="og:type" />
<meta content="http://tech.skbkontur.ru" property="og:url" />
<meta content="Open source технологии и решения компании СКБ Контур: Moira, DiTrace и многое другое - Технологии Контура" property="og:title" />
<meta content="Технологии Контура" property="og:site_name" />
<meta content="Open source технологии компании СКБ Контур. Moira — решение по уведомлениям из Graphite, DiTrace — трассировка запросов в распределенных системах и другие решения" property="og:description" />
<meta content="http://tech.skbkontur.ru/2c310c5fc1154922a96823017cd30fde.png" property="og:image" />
```

Сейчас у нас некоторые атрибуты без кавычек
`<meta data-react-helmet=true content=article property=og:type>
<meta data-react-helmet=true content=http://tech.skbkontur.ru property=og:url>`
 и адрес на лого относительный, а нужно прямой 
`<meta data-react-helmet=true content=/2c310c5fc1154922a96823017cd30fde.png property=og:image>`

**Comment by beevee** [comment]
Женя, надо допилить

**Comment by beevee** [comment]
Предлагаю рисование всех кастомных картинок отложить на послерелиза. У нас тут lean startup, надо экономно запустить сайт :)

**Comment by tihonove** [comment]
Кавычки вернул, абсолютный урл поставил. Кроме og:image сделал абсолютный урл ещё тут:
`<link href="http://tech.skbkontur.ru/2c310c5fc1154922a96823017cd30fde.png" rel="image_src">`
@safarov , поправь если так делать не надо было

**Comment by safarov** [comment]
Зашибись же
![image](https://cloud.githubusercontent.com/assets/2157406/19533098/d0fb2d4e-9657-11e6-902e-40d39e342707.png)
![image](https://cloud.githubusercontent.com/assets/2157406/19533114/e6d4e0ba-9657-11e6-94ea-30a178712fcc.png)
а про 

`<link href="http://tech.skbkontur.ru/2c310c5fc1154922a96823017cd30fde.png" rel="image_src">`
круто, что сделал, так и нужно было

**Comment by safarov** [comment]
задачку закрываем, молодцы
