### ISSUE TITLE
Косяк верстки на главной

### ISSUE THREAD

**Issue by beevee** [skbkontur/skbkontur.github.io#24]
![2016-10-17_20-28-46](https://cloud.githubusercontent.com/assets/1009675/19444095/7c2c1e5a-94a8-11e6-9a09-dfebed74805f.png)

**Comment by tihonove** [comment]
Короче баг я поправил, но мне не нравится как. Помечу как непонятно

**Comment by tihonove** [comment]
Исправил более правильным способом
