### ISSUE TITLE
Заголовок страницы должен содержать не только название раздела, но какой-то общий контекст

### ISSUE THREAD

**Issue by tihonove** [skbkontur/skbkontur.github.io#25]

**Comment by tihonove** [comment]
По следам #19

**Comment by tihonove** [comment]
В этом комите видно, как сделать заголовок с общим куском

**Comment by beevee** [comment]
Я не понимаю, откуда следует такое требование, и поэтому не понимаю, что туда писать :(

**Comment by tihonove** [comment]
Когда я открываю навигацию, прикольно там видеть не только заголовок, но и откуда эта страница взялась. Например как вот тут:
![navigation](https://cloud.githubusercontent.com/assets/2770182/19474310/7858465a-9548-11e6-9d71-0accea3f6d9b.png)
Ну и в хистори браузера тоже поможет, при поиске например.

**Comment by beevee** [comment]
Ну тогда пусть как сейчас остается, нормально :)
