### ISSUE TITLE
Добавить meta-тэги

### ISSUE THREAD

**Issue by tihonove** [skbkontur/skbkontur.github.io#3]

**Comment by tihonove** [comment]
Лёша, короче, возможность добавлять тэги я добавил. Даже чё-то написал туда. 
Я тут немного погуглил, чтобы найти этот сайт. Снипет у него очень уродский. Можешь ли ты попытаться как-то привлечь какого-нибудь нашего СЕОшника? Он бы мог мне подсказать как правильно организовать верстку. Мне это и самому интересно узнать, но не настолько чтобы самому всю эту тему раскапывать.

**Comment by beevee** [comment]
Так, давай мы конкретно этот таск закроем, потому что возможность прописывать теги теперь есть. Я заведу новый, с другим описанием.
