### ISSUE TITLE
Придумать, как отображать длинные названия Open Source продуктов

### ISSUE THREAD

**Issue by tihonove** [skbkontur/skbkontur.github.io#33]
Иллюстрация того, как будет сейчас:

![image](https://cloud.githubusercontent.com/assets/2770182/19818466/4fee2788-9d69-11e6-928b-b819d254d9d0.png)

По мотивам #32

**Comment by igorlukanin** [comment]
А уменьшенное межстрочное расстояние для заголовка не решает проблему?

```css
h3 {
  line-height: 1.25em;
}
```

<img width="724" alt="screen shot 2017-02-24 at 20 44 27" src="https://cloud.githubusercontent.com/assets/3852894/23309859/1eb639f0-fad2-11e6-95cf-4b25c7bbd3c6.png">
