### ISSUE TITLE
Добавить Modulizer в список Open Source-проектов

### ISSUE THREAD

**Issue by igorlukanin** [skbkontur/skbkontur.github.io#37]
https://github.com/Falkeyn/Modulizer — его сделал @falkeyn, а пользуются диазйнеры Контура.

**Comment by beevee** [comment]
Он без открытой лицензии :( Более того, копирайт стоит!

**Comment by igorlukanin** [comment]
@beevee, упс!

**Comment by Falkeyn** [comment]
А что нужно сделать? И это нормально, если дизайнерские плагины для Скетча будут вперемешку с фреймворками для веб-сервисов?
