### ISSUE TITLE
Добавить UXperiment Sketch Plugin

### ISSUE THREAD

**Issue by igorlukanin** [skbkontur/skbkontur.github.io#38]
Катя Мохова сказала, что можно добавить сюда плагин для Скетча, который используется в [UXperiment](https://uxperiment.io) для экспорта прототипов.

Вот репозиторий: https://github.com/igorlukanin/uxperiment-sketch-plugin/tree/master

Я добавил лицензию, написал README. Что-нибудь ещё сделать?

**Comment by beevee** [comment]
Напиши короткое описание по-русски и по-английски, как у других проектов на сайте. Я думаю, у тебя лучше получится это сделать :)

Можно ставить ссылки.

**Comment by beevee** [comment]
И если иконка/логотип есть, то давай тоже.

**Comment by igorlukanin** [comment]
Описание:
> Плагин для трансформации [Sketch](https://sketchapp.com)-документов в JSON-объекты
> A plugin that transforms [Sketch](https://sketchapp.com) documents into JSON objects

Иконки нет.

**Comment by beevee** [comment]
Сделано в 5eac4a34c0188ac7c06442d7a267f77b909a9f37.
