### ISSUE TITLE
Проверить как выглядит на маке

### ISSUE THREAD

**Issue by tihonove** [skbkontur/skbkontur.github.io#4]

**Comment by beevee** [comment]
![2016-09-26_16-55-40](https://cloud.githubusercontent.com/assets/1009675/18833468/3f11a6ce-840a-11e6-8e9f-c098144779bf.png)
![2016-09-26_16-56-19](https://cloud.githubusercontent.com/assets/1009675/18833469/3f13b8ec-840a-11e6-93a6-bf39acac497e.png)

**Comment by beevee** [comment]
Segoe UI у меня не установлен.

**Comment by beevee** [comment]
Все ок, закрываем?
