### ISSUE TITLE
Обновить retail-ui

### ISSUE THREAD

**Issue by igorlukanin** [skbkontur/skbkontur.github.io#40]
Я добавил в подвал ссылку на канал в Телеграме. Хотел для неё использовать иконку Телеграма из иконочного шрифта. Но её нет в той версии retail-ui, которая используется на сайте.

Поэтому я решил обновить retail-ui в `package.json`:

```
–    "retail-ui": "^0.4.17",
+    "retail-ui": "^0.9.0",
```

После этого сломалась сборка:

```
ERROR in ./~/retail-ui/components/Link/Link.js
Module build failed: SyntaxError: Unexpected token (37:51)

  35 |   href?: string,
  36 |   icon?: string,
> 37 |   onClick?: (SyntheticMouseEvent<HTMLLinkElement>) => void,
     |                                                    ^
  38 |   use?: 'default' | 'success' | 'danger' | 'grayed',
  39 |   children?: React.Node,
  40 |   _button?: boolean,

 @ ./~/retail-ui/components/Link/index.js 7:12-29
```

Как я понял, не нравится стрелочная лямбда в коде компонента Link. Но почему — я не понял.

Что пробовал:

* посмотрел конфиг Вебпака, помедитировал на конфиг из [README retail-ui](https://github.com/skbkontur/retail-ui), пошаманил, но не смог победить
* проверил версию NodeJS на своей машине — 8.4.0 (свежая)

Больше идей нет. @tihonove, поможешь?

**Comment by igorlukanin** [comment]
@nanot1m, может быть, ты подскажешь, как это починить? :)

**Comment by nanot1m** [comment]
@igorlukanin, достаточно обновить babel. До какой версии нужно обновить не помню

**Comment by nanot1m** [comment]
> Как я понял, не нравится стрелочная лямбда в коде компонента Link. Но почему — я не понял.

Ему не нравится краткая запись определения типа (тут нет имени аргумента).

**Comment by igorlukanin** [comment]
Обновил пакеты — всё получилось.
